### ISSUE TITLE
Deactivating and activating the plugin multiplied the dropdown fields

### ISSUE THREAD

**Issue by per4mance** [shanebp/BP-Timezones#1]
Hi,
after deactivating and activating your plugin the dropdown fields multiplied. It's not possible to delete your dropdown field from registration form.

Second, I cannot see if your plugin has to be activated or not for using?

Help would be great!

https://www.pragabuch.org/registrierung/

Best Regards,
Thorsten

**Comment by shanebp** [comment]
You cannot delete the fields because 'can_delete' was set to false in loader.php. 
 I've changed that to 'true' so other users won't have your problem.

But for your problem, you will have to directly edit the database.
It will be easy if you have access to phpMyAdmin.
Go to your database and delete all the entries you don't want from the bp_xprofile_fields table.

If you still want to use the plugin after that, download it again so that you can delete fields from the wp-admin > Users > Profile Fields screen.

If the plugin is not activated, timestamps on messages will not reflect the member's choice re timezone.

It only affects the displayed timestamp on messages.
It could be extended to affect other timestamps.

The plugin is not comprehensive - it was written long ago as an experiment re some other discussion.

Steps:
1. Deactivate and delete the plugin.
2. Clean up the database
3. Get the new version from Github and adjust the field name you want in BOTH places.
